// Debug: verifica se o proxy/servidor de IA está acessível (sem logar keys)
console.log('=== DEBUG AI PROXY ===')
console.log('Ambiente:', import.meta.env.MODE)
console.log('NODE_ENV:', import.meta.env.NODE_ENV)
console.log('API keys NÃO são mais expostas no client.')
console.log('Use /api/gemini/* e /api/groq/* com login autenticado.')
console.log('========================')
